apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-nautilus
spec:
  template:
    metadata:
      name: countdown-nautilus
    spec:
      containers:
      - name: container-countdown-nautilus
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep 5"]
      restartPolicy: Never